// /login — re-authenticate a Claude Code session from Telegram.
//
// Claude's OAuth token gets revoked periodically (observed ~12h on some
// accounts); the agent then prints "Please run /login · API Error: 401
// OAuth access token has been revoked" and sits there. The only
// remediation is the CLI's own /login dialog, and its OAuth URL carries
// a PKCE code_challenge generated by that very process — so the link
// cannot be pre-made, it has to be driven inside the live session.
// That is exactly what this does, entirely through the bridge's two
// existing primitives: screen snapshots (read) and injectSay (the one
// sanctioned PTY write):
//
//  1. type "/login" + Enter, wait for the "Select login method" picker;
//  2. press Enter (option 1, Claude subscription) and wait for the
//     "Use the url below to sign in" screen;
//  3. scrape the https://…/oauth/authorize?… URL and send it to the
//     chat; ARM the chat so its next plain-text message is pasted as
//     the code (Claude then shows "Paste code here if prompted >").
//
// Live capture of the dialog (Claude Code v2.1.238) pinned the three
// screen markers the state machine keys on.
package telegram

import (
	"context"
	"fmt"
	"regexp"
	"strings"
	"time"
)

// Login-dialog screen markers (whitespace-insensitive substring match on
// the normalized screen — the CLI positions words with cursor escapes,
// so stripped lines can lose their spaces).
const (
	loginPickerMarker = "selectloginmethod"
	loginURLMarker    = "usetheurlbelowtosignin"
	loginPasteMarker  = "pastecodehere"
)

// oauthURLPattern finds the authorize URL on the login screen. The URL
// may be wrapped across screen lines by the terminal, so callers feed a
// whitespace-collapsed screen.
var oauthURLPattern = regexp.MustCompile(`https://[a-z0-9.-]+/[^\s]*oauth/authorize\?[^\s"'<>]+`)

// loginStepTimeout bounds each dialog transition wait.
const loginStepTimeout = 20 * time.Second

// cmdLogin drives the live session's /login dialog and relays the URL.
func (b *Bridge) cmdLogin(ctx context.Context, chatID int64) {
	if !b.requireRunner(ctx, chatID) {
		return
	}
	projectID, ok := b.chatProject(ctx, chatID)
	if !ok {
		return
	}
	sess, live := b.runningSession(projectID)
	if !live {
		b.reply(ctx, chatID, "No agent is running for this project — start one (just type) and then /login.")
		return
	}
	if sess.Snapshot == nil {
		b.reply(ctx, chatID, "This session has no screen to read — /login needs one.")
		return
	}

	// Already on the URL screen (e.g. someone typed /login in the GUI)?
	// Skip straight to relaying it.
	if url := b.loginURLOnScreen(sess); url != "" {
		b.relayLoginURL(ctx, chatID, projectID, url)
		return
	}

	b.sendTyping(ctx, chatID)
	if err := b.injectSay(projectID, "/login"); err != nil {
		b.reply(ctx, chatID, "Couldn't type /login into the session: "+EscapeHTML(err.Error()))
		return
	}
	if !b.waitScreen(ctx, sess, func(s string) bool {
		return strings.Contains(s, loginPickerMarker) || strings.Contains(s, loginURLMarker)
	}) {
		b.reply(ctx, chatID, "The login dialog didn't appear. /screen shows the session's current state.")
		return
	}
	if b.loginURLOnScreen(sess) == "" {
		// Method picker: option 1 (Claude subscription) is preselected —
		// a lone Enter chooses it.
		if err := b.injectSay(projectID, ""); err != nil {
			b.reply(ctx, chatID, "Couldn't confirm the login method: "+EscapeHTML(err.Error()))
			return
		}
		if !b.waitScreen(ctx, sess, func(s string) bool { return strings.Contains(s, loginURLMarker) }) {
			b.reply(ctx, chatID, "The sign-in link didn't appear. /screen shows the session's current state.")
			return
		}
	}
	url := b.loginURLOnScreen(sess)
	if url == "" {
		b.reply(ctx, chatID, "The login screen is up but I couldn't read the sign-in link — /screen to see it.")
		return
	}
	b.relayLoginURL(ctx, chatID, projectID, url)
}

// relayLoginURL sends the sign-in link and arms the chat for the code.
func (b *Bridge) relayLoginURL(ctx context.Context, chatID int64, projectID, url string) {
	b.mu.Lock()
	b.loginPending[chatID] = projectID
	b.mu.Unlock()
	b.reply(ctx, chatID, strings.Join([]string{
		"🔐 <b>Sign in to Claude</b> — open this link, approve, and copy the code it shows:",
		url,
		"",
		"Then just send me the code here and I'll paste it into the session.",
	}, "\n"))
}

// handleLoginCode consumes the code for an armed chat: pastes it into
// the session (injectSay — text then Enter), disarms, and reports.
// Returns false when the chat wasn't armed (the caller treats the text
// as ordinary conversation).
func (b *Bridge) handleLoginCode(ctx context.Context, chatID int64, text string) bool {
	b.mu.Lock()
	projectID, armed := b.loginPending[chatID]
	if armed {
		delete(b.loginPending, chatID)
	}
	b.mu.Unlock()
	if !armed {
		return false
	}
	code := strings.TrimSpace(text)
	if strings.EqualFold(code, "cancel") {
		b.reply(ctx, chatID, "Login cancelled — I won't paste anything.")
		return true
	}
	if err := b.injectSay(projectID, code); err != nil {
		b.reply(ctx, chatID, "Couldn't paste the code: "+EscapeHTML(err.Error()))
		return true
	}
	b.reply(ctx, chatID, "✅ Code pasted. If Claude accepts it the session resumes on its own; /screen to check.")
	return true
}

// loginURLOnScreen scrapes the OAuth URL from the session's current
// screen, joining wrapped lines first.
func (b *Bridge) loginURLOnScreen(sess *WatchedSession) string {
	if sess.Snapshot == nil {
		return ""
	}
	joined := strings.Join(strings.Fields(normalizeScreen(sess.Snapshot())), "")
	// Field-joining removed the spaces; the URL itself never contains
	// spaces, and the marker text around it is matched separately.
	return oauthURLPattern.FindString(joined)
}

// waitScreen polls the session's normalized, whitespace-collapsed,
// lower-cased screen until pred holds or the step times out.
func (b *Bridge) waitScreen(ctx context.Context, sess *WatchedSession, pred func(string) bool) bool {
	deadline := time.Now().Add(loginStepTimeout)
	for time.Now().Before(deadline) && ctx.Err() == nil {
		if sess.Snapshot != nil {
			s := strings.ToLower(strings.Join(strings.Fields(normalizeScreen(sess.Snapshot())), ""))
			if pred(s) {
				return true
			}
		}
		b.sleepFn(ctx, b.chatStartPoll)
	}
	return false
}

// loginHint is the auto-relay text when the watched session raises an
// auth_required issue: one message, once per session, pointing at /login.
func loginHint(sess *WatchedSession) string {
	return fmt.Sprintf("🔐 Claude's login expired on <b>%s</b> (\"Please run /login\"). Send /login and I'll walk the session through re-auth — you approve on your phone, then send me the code.", EscapeHTML(sessionStateLine(sess)))
}
